### ISSUE TITLE
Options are not fully displayed

### ISSUE THREAD

**Issue by NkxPanda** [NicholasAzar/ng-selectize#54]
Hello,

I'm currently using ng2-selectize and I'm facing an issue trying to display options. My component looks like this :
     
`<ng2-selectize [config]="config"></ng2-selectize>`

When I give selectize an array of strings, it interprets it quite well but when I am passing it an array of OBJECT, the render is not what I expect since it only displays ONE option.

Here is my array:

```
    var exampleArray = [
      {name: 'A', id: 1},
      {name: 'B', id: 2},
      {name: 'C', id: 3},
      {name: 'D', id: 4},
      {name: 'E', id: 5},
      {name: 'F', id: 6},
      {name: 'G', id: 15},
      {name: 'H', id: 23},
      {name: 'I', id: 90},
    ];
```

My options looks like : 
```
this.options = [];
for (var i = 0; i < exampleArray.length;  i++) {
    this.options.push({value: exampleArray[i]});
}
```

And my configuration looks like this :

```
    this.config = {
        labelField: 'label',
        valueField: 'value',
        highlight: false,
        create:false,
        persist:true,
        plugins: ['dropdown_direction', 'remove_button'],
        dropdownDirection: 'down',
        maxItems: 5,
        options: this.options,
        render: {
          item: (data) => {
            console.log('selecting item', data);
          },
          option: (data) => {
            console.log('instantiating option', data);
          }
        },
      };
```

Actually, the function render.option is only called ONCE (which explains why it only displays one option) but I don't know why since my array length is equal to 9.

Can someone enlighten me please ? Thank you.

**BONUS** **question** : is it possible to extract raw data when an option is selected or removed ? By raw data I mean object, because selectize only seems to return strings which I find quite unfortunate...

**Comment by NicholasAzar** [comment]
Hi @NkxPanda , instead of passing your options through [config], try using the [options] input. Reason for this is the difficulty detecting changes to options passed in through the config... whereas [options] would be reactive to change.

I'm not sure about returning the entire object rather then just the value.. if you needed to you could always set the value field as a unique key in your list of objects and on selection look through your options for that key.. but yeah, not sure about an easier way.. sorry.
